### PR TITLE
Merge ASW from `vespaman/serial-dma` branch.

### PR DESCRIPTION
**Pull request by hydra**
This PR merges in only the ASW changes from @vespaman

I tried this on a feeder on my 48VB which was repeatedly getting stuck and confirm it works for me.

### CODE REVIEW

**Comment by janm012012** [comment]
Hi @hydra!

Many thanks for factoring this out of the giant PR #1. That makes reviewing and merging much easier.

I like the AWS code in general but have some doubts with it in its current state:

- it should be noted, that by adding this code, the performance might be degraded as it will hide bad drag pin setup. I'd recommend to regularly grep the log files for "AWS" to detect if this code was required for the requested drag operation.
- some changes in config.default are just spaces/tabs. I'd rather keep the original state.
- the dragpin sensor is hardcoded. IIRC @vespaman had arguments why this can not be made configurable therefore I think a message to the console should reflect that in case the firmware is ever used for something else then a CMH-T.
- the commend for the g-code "M204 S1000" is not correct.
- the g-code "M204 S1000" changes the acceleration of all following commands. That's against the NIST standard. We either have to remove this code or revert to the previous value. Could you verify if the wigging still works if executed at other (e.g. full) speeds (1000mm/s^2 is very slow)?
- the release_try[] array shall be defined as static and constant to limit its scope to this module and store it in flash.
- I'd love to see Pin::from_string_no_init() and Pin::from_string() sharing code when possible.

Jan

**Comment by hydra** [comment]
Hi @janm012012 

I didn't go though much of the wiggle code in detail.

It would help if you made you comments against the actual lines of code in the github review as it makes the conversations relating to specific bits of code easier to track and follow.  You can suggest changes there too.

IIRC there was an encoding change, I have a commit for that somewhere.

Good IDEs by default trim and trailing whitespace, this is what IntelliJ Idea does by default, I'd prefer a PR that did this step to the entire codebase so that going forwards we have a well defined style.  It's possible to setup a linter as a github action to check for this too.

I will try to remove the M204 S1000 and retest.

What is the NIST standard you refer too, I'm a n00b when it comes to g-code and all this stuff.

I don't plan on making many changes to smoothieware or getting to learn the code base, to me it's a means to an end right now.  

I extracted this code because my dragpin was always getting stuck no-matter what i tried in OpenPnP and needed a solution that worked.  I agree with you that use of ASW indicates an less than ideal setup, the OpenPnP issue solver is the place for this ASW checking I feel.

**Comment by hydra** [comment]
@janm012012 today I tested ASW without the M204 command and it works fine still.

**Comment by janm012012** [comment]
Hi @hydra!

Many thanks for provide this PR! I've just merged it as part of PR #3 an along side other drag pin related mods @vespaman has provided after careful reviewing and testing.

I'm sorry that it has take so long.

Jan

**Pull request closed without merging**
